import { Project, Skill, Milestone, CodingStat } from './types';

export const PERSONAL_INFO = {
  name: 'Priyanka Snale',
  title: 'B.Tech student in Computer Science & Engineering',
  university: 'Indian Institute of Technology / B.Tech CSE',
  cgpa: '9.45 / 10.0',
  tagline: 'Crafting responsive full-stack applications and analyzing algorithms with colorful designs and creative problem-solving.',
  aboutLong: 'I am a pre-final year B.Tech Computer Science & Engineering student driven by a passion for building interactive software, mastering algorithms, and exploring distributed systems. I believe code should not only compile but also look spectacular and offer delightful, intuitive user interfaces. With a strong base in Data Structures, OS, and DBMS, I build optimized web systems, participate in national hackathons, and constantly test standard engineering limits.',
  github: 'https://github.com/priyankasnale',
  linkedin: 'https://linkedin.com/in/priyankasnale',
  email: 'priyankasnale@gmail.com',
};

export const CODING_STATS: CodingStat[] = [
  {
    label: 'LeetCode / DSA',
    value: '650+ Solved',
    subText: 'Knight badge, Top 4% rank globally',
    iconName: 'Code',
    colorClass: 'from-pink-500 via-orange-500 to-yellow-500',
  },
  {
    label: 'GitHub Commits',
    value: '950+ This Year',
    subText: 'Daily green streak, active contributor',
    iconName: 'GitMerge',
    colorClass: 'from-purple-500 via-indigo-500 to-blue-500',
  },
  {
    label: 'Hackathons',
    value: '3 Wins / 5 Active',
    subText: 'Smart India Hackathon national finalist',
    iconName: 'Trophy',
    colorClass: 'from-teal-400 via-emerald-500 to-cyan-500',
  },
  {
    label: 'Total Codebases',
    value: '22+ Audited',
    subText: 'Full-stack repositories & server assets',
    iconName: 'FolderCode',
    colorClass: 'from-yellow-400 via-pink-500 to-purple-500',
  },
];

export const SKILLS_DATA: Skill[] = [
  // Languages
  {
    name: 'C++',
    level: 92,
    category: 'Languages',
    iconName: 'Binary',
    colorClass: 'from-blue-500 to-cyan-500',
    bgGlowClass: 'rgba(59, 130, 246, 0.15)',
  },
  {
    name: 'Java',
    level: 85,
    category: 'Languages',
    iconName: 'Coffee',
    colorClass: 'from-red-500 to-orange-500',
    bgGlowClass: 'rgba(239, 68, 68, 0.15)',
  },
  {
    name: 'Python',
    level: 88,
    category: 'Languages',
    iconName: 'Terminal',
    colorClass: 'from-yellow-500 to-green-500',
    bgGlowClass: 'rgba(234, 179, 8, 0.15)',
  },
  {
    name: 'TypeScript',
    level: 90,
    category: 'Languages',
    iconName: 'FileCode',
    colorClass: 'from-blue-600 to-indigo-500',
    bgGlowClass: 'rgba(79, 70, 229, 0.15)',
  },
  {
    name: 'SQL & DBMS',
    level: 87,
    category: 'Languages',
    iconName: 'Database',
    colorClass: 'from-emerald-500 to-teal-500',
    bgGlowClass: 'rgba(16, 185, 129, 0.15)',
  },

  // Frontend
  {
    name: 'React.js',
    level: 95,
    category: 'Frontend',
    iconName: 'Atom',
    colorClass: 'from-cyan-400 to-blue-500',
    bgGlowClass: 'rgba(34, 211, 238, 0.15)',
  },
  {
    name: 'Next.js',
    level: 88,
    category: 'Frontend',
    iconName: 'Compass',
    colorClass: 'from-slate-200 to-slate-500',
    bgGlowClass: 'rgba(255, 255, 255, 0.1)',
  },
  {
    name: 'Tailwind CSS',
    level: 94,
    category: 'Frontend',
    iconName: 'Palette',
    colorClass: 'from-teal-400 to-emerald-400',
    bgGlowClass: 'rgba(20, 184, 166, 0.15)',
  },
  {
    name: 'Motion (Framer)',
    level: 85,
    category: 'Frontend',
    iconName: 'Zap',
    colorClass: 'from-purple-500 to-pink-500',
    bgGlowClass: 'rgba(139, 92, 246, 0.15)',
  },

  // Backend & DB
  {
    name: 'Node.js & Express',
    level: 90,
    category: 'Backend & DB',
    iconName: 'Cpu',
    colorClass: 'from-green-500 to-emerald-600',
    bgGlowClass: 'rgba(34, 197, 94, 0.15)',
  },
  {
    name: 'PostgreSQL',
    level: 86,
    category: 'Backend & DB',
    iconName: 'Database',
    colorClass: 'from-indigo-400 to-blue-600',
    bgGlowClass: 'rgba(99, 102, 241, 0.15)',
  },
  {
    name: 'MongoDB',
    level: 83,
    category: 'Backend & DB',
    iconName: 'Server',
    colorClass: 'from-green-600 to-yellow-600',
    bgGlowClass: 'rgba(22, 163, 74, 0.15)',
  },
  {
    name: 'Redis Cache',
    level: 78,
    category: 'Backend & DB',
    iconName: 'Flame',
    colorClass: 'from-rose-500 to-red-600',
    bgGlowClass: 'rgba(244, 63, 94, 0.15)',
  },

  // Core CS Fundamentals
  {
    name: 'Data Structures & Algos',
    level: 95,
    category: 'Core CS Fundamentals',
    iconName: 'Network',
    colorClass: 'from-pink-500 to-purple-600',
    bgGlowClass: 'rgba(236, 72, 153, 0.15)',
  },
  {
    name: 'Operating Systems',
    level: 88,
    category: 'Core CS Fundamentals',
    iconName: 'Settings',
    colorClass: 'from-orange-500 to-yellow-500',
    bgGlowClass: 'rgba(249, 115, 22, 0.15)',
  },
  {
    name: 'Computer Networks',
    level: 86,
    category: 'Core CS Fundamentals',
    iconName: 'Globe',
    colorClass: 'from-blue-500 to-indigo-600',
    bgGlowClass: 'rgba(59, 130, 246, 0.15)',
  },
  {
    name: 'Database Architecture',
    level: 89,
    category: 'Core CS Fundamentals',
    iconName: 'TableProperties',
    colorClass: 'from-amber-500 to-orange-600',
    bgGlowClass: 'rgba(245, 158, 11, 0.15)',
  },

  // Developer Tools
  {
    name: 'Git & GitHub Workflow',
    level: 92,
    category: 'Developer Tools',
    iconName: 'GitBranch',
    colorClass: 'from-stone-400 to-stone-700',
    bgGlowClass: 'rgba(255, 255, 255, 0.1)',
  },
  {
    name: 'Docker Containers',
    level: 81,
    category: 'Developer Tools',
    iconName: 'Layers',
    colorClass: 'from-sky-500 to-blue-600',
    bgGlowClass: 'rgba(14, 165, 233, 0.15)',
  },
  {
    name: 'Linux / Shell Scripting',
    level: 84,
    category: 'Developer Tools',
    iconName: 'Terminal',
    colorClass: 'from-violet-500 to-fuchsia-500',
    bgGlowClass: 'rgba(139, 92, 246, 0.15)',
  },
];

export const PROJECTS_DATA: Project[] = [
  {
    id: 'algo-visuals',
    title: 'AlgoVisuals Engine',
    description: 'An interactive React-based data structures and sorting algorithm simulator featuring sound design and interactive performance charts.',
    longDescription: 'Developed an immersive visualizer for sorting, pathfinding, and data structures. It displays step-by-step state changes, comparison metrics, array operations, and compares time complexity (O(N log N) vs O(N²)) in real-time. Designed specifically to help peer CSE students grasp structural computer science concepts visually.',
    technologies: ['React.js', 'Motion', 'Tailwind CSS', 'Web Audio API'],
    category: 'DSA',
    simulationType: 'sorting',
    githubUrl: 'https://github.com/priyankasnale/algo-visuals-engine',
    stats: [
      { label: 'Array Range', value: '5 to 40 items' },
      { label: 'Time Saved', value: '45% in teaching' },
      { label: 'Algorithms', value: 'Bubble, Selection, Insertion, Quick' },
    ],
    keyFeatures: [
      'Interactive control block (Play, Pause, Speed adjustment)',
      'Web Audio frequency generator mapping high indices to high pitches',
      'Realistic comparative graph comparing standard execution loops',
    ],
  },
  {
    id: 'auradb-schema',
    title: 'AuraDB Schema Visualizer',
    description: 'A dynamic database design and SQL schema utility allowing users to design custom tables and auto-generate relational migration scripts.',
    longDescription: 'A custom student tool supporting database validation! Users can create logical tables, configure attributes, define primary and foreign keys, choose data types, and preview normalized relational schemas instantly alongside correct DDL scripts.',
    technologies: ['TypeScript', 'React', 'Motion', 'PostgreSQL Dialect'],
    category: 'Systems',
    simulationType: 'database',
    githubUrl: 'https://github.com/priyankasnale/auradb-visualizer',
    stats: [
      { label: 'Generated Scripts', value: 'Postgres & MySQL' },
      { label: 'Validation Layers', value: '1NF, 2NF, 3NF Checklists' },
      { label: 'Tables Simulated', value: 'Up to 5 at once' },
    ],
    keyFeatures: [
      'Interactive physical schema drawing sandbox',
      'One-click syntax highlight for target SQL DDL scripts',
      'Comprehensive DBMS design indicators explaining normal forms',
    ],
  },
  {
    id: 'netpath-sim',
    title: 'NetPath Packet Router',
    description: 'A responsive network layers visualizer exhibiting Dijkstra routing paths, routing metrics, and dynamic packet collision algorithms.',
    longDescription: 'Implements a visual simulation of the Open Shortest Path First (OSPF) protocol in Computer Networks. Users can add or drop nodes, trigger route failures, and send interactive colorful data packets across a custom mesh, reporting routing updates, hop limits, and packet losses.',
    technologies: ['React.js', 'D3 Canvas', 'Tailwind', 'Motion'],
    category: 'Systems',
    simulationType: 'networking',
    githubUrl: 'https://github.com/priyankasnale/netpath-packet-router',
    stats: [
      { label: 'Protocols Explained', value: 'OSPF & RIP Routing' },
      { label: 'Loss Simulation', value: 'Variable (0% to 50%)' },
      { label: 'Hop Limit (TTL)', value: '30 max' },
    ],
    keyFeatures: [
      'Editable Network Mesh (place routers, adjust link latency weights)',
      'Real-time simulation displaying Dijkstra algorithm calculations',
      'Vivid visual trace demonstrating network collision & TCP handshake states',
    ],
  },
  {
    id: 'neurosense-nlp',
    title: 'NeuroSense Smart Classifier',
    description: 'An AI-driven visual client-side assistant classifying input text into emotional states and showing confidence vectors.',
    longDescription: 'Built as an exploration into Natural Language Processing. It tokenizes user inputs local-first, matches keywords, assigns TF-IDF vector states, and displays neural activation thresholds and confidence scores across multi-colored metrics dashboards.',
    technologies: ['Python', 'scikit-learn', 'React', 'Recharts'],
    category: 'AI & ML',
    simulationType: 'none',
    githubUrl: 'https://github.com/priyankasnale/neurosense-classifier',
    stats: [
      { label: 'Model Accuracy', value: '89.4% Dev Set' },
      { label: 'Latency', value: '< 15ms locally' },
      { label: 'Vocabulary Size', value: '1k+ stems' },
    ],
    keyFeatures: [
      'Live classification preview reacting to typing state instantly',
      'Dynamic activation score meters with colorful radial graphs',
      'Detailed analytical text report containing top vector components',
    ],
  },
];

export const MILESTONES_DATA: Milestone[] = [
  {
    id: 'm1',
    semester: 'Pre-Final Year B.Tech',
    period: 'May 2026 - Present',
    title: 'Software Engineer Intern',
    subtitle: 'Nirmala Labs & Systems',
    achievements: [
      'Refactored server response middleware, improving system throughput by 14%.',
      'Developed 8 custom high-performance data pipeline interfaces using React and Node.js.',
      'Configured automated CI/CD configurations, streamlining pull requests and review cycles.',
    ],
    type: 'internship',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
  },
  {
    id: 'm2',
    semester: 'B.Tech Semester 6',
    period: 'Jan 2026 - May 2026',
    title: 'Smart India Hackathon Finalist',
    subtitle: 'Ministry of Education, GoI',
    achievements: [
      'Led "Team Recursion" to build an offline-first crisis relief resource-mapping database dashboard.',
      'Developed a resilient Sync-Engine operating peer-to-peer across local WiFi routers.',
      'Honored with the top creative engineering runner-up prize for core network integration.',
    ],
    type: 'hackathon',
    badgeColor: 'bg-fuchsia-500/10 text-fuchsia-400 border-fuchsia-500/20',
  },
  {
    id: 'm3',
    semester: 'B.Tech Semester 5',
    period: 'Jul 2025 - Dec 2025',
    title: 'Google Girl Hackathon Top Finalist',
    subtitle: 'Google India',
    achievements: [
      'Qualified for national final circles among 18,000 algorithmic competitors from premier engineering universities.',
      'Designed and coded optimized algorithmic modules under 3-hour constraints using Java and C++.',
      'Mentored by seasoned Google staff in scalable design-patterns and modern cloud hosting architectures.',
    ],
    type: 'hackathon',
    badgeColor: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20',
  },
  {
    id: 'm4',
    semester: 'B.Tech Semester 4',
    period: 'Jan 2025 - Jun 2025',
    title: 'Academics & DSA Foundations',
    subtitle: 'IIT (CSE Academic Track)',
    achievements: [
      'Maintained a stellar 9.45 / 10.0 CGPA; ranked in Top 5% of B.Tech CSE department.',
      'Aced Data Structures & Algorithms (98% score) and Database Systems courses (95% score).',
      'Developed and shared the AlgoVisuals educational engine for peer tutoring.',
    ],
    type: 'academic',
    badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
  },
];
